export class DatabaseConstants {
  static USERS_REPOSITORY = "USERS_REPOSITORY";
  static AUTHORS_REPOSITORY = "AUTHORS_REPOSITORY";
  static BOOKS_REPOSITORY = "BOOKS_REPOSITORY";
  static BOOKSAUTHORS_REPOSITORY = "BOOKSAUTHORS_REPOSITORY";
  static USERLIST_REPOSITORY = "USERLIST_REPOSITORY";
}
